import 'dotenv/config';
import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Dresses (6 products)
        {
            name: 'Cove Cashmere Oversized Crew Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '298.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1316169WYM.jpg',
            stock: 24,
            sku: '1316169WYM',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Jillian Silk Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '248.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1318344BLK.jpg',
            stock: 18,
            sku: '1318344BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Veda Linen Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '198.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1318345NVY.jpg',
            stock: 32,
            sku: '1318345NVY',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Petites Juliette Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '218.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1319876CRM.jpg',
            stock: 15,
            sku: '1319876CRM',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Kourtney Denim Midi Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '168.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1320123BLU.jpg',
            stock: 28,
            sku: '1320123BLU',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Bea Linen Dress',
            description: 'Sustainable and timeless piece from Reformation',
            price: '178.00',
            category: 'dresses',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1320456WHT.jpg',
            stock: 22,
            sku: '1320456WHT',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Sweaters/Tops (5 products)
        {
            name: 'Cashmere Relaxed Crew',
            description: 'Sustainable and timeless piece from Reformation',
            price: '198.00',
            category: 'sweaters',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1320789BEG.jpg',
            stock: 35,
            sku: '1320789BEG',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Cashmere Relaxed Vneck',
            description: 'Sustainable and timeless piece from Reformation',
            price: '198.00',
            category: 'sweaters',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1321012GRY.jpg',
            stock: 41,
            sku: '1321012GRY',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Marlee Knit Top',
            description: 'Sustainable and timeless piece from Reformation',
            price: '128.00',
            category: 'tops',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1321345IVY.jpg',
            stock: 29,
            sku: '1321345IVY',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Alessi Top',
            description: 'Sustainable and timeless piece from Reformation',
            price: '98.00',
            category: 'tops',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1321678PNK.jpg',
            stock: 38,
            sku: '1321678PNK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Sofia Ribbed Tank',
            description: 'Sustainable and timeless piece from Reformation',
            price: '78.00',
            category: 'tops',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1321901BLK.jpg',
            stock: 45,
            sku: '1321901BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Bottoms (4 products)
        {
            name: 'Cary High Rise Slouchy Wide Leg Jeans',
            description: 'Sustainable and timeless piece from Reformation',
            price: '168.00',
            category: 'bottoms',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1322234DEN.jpg',
            stock: 26,
            sku: '1322234DEN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Cary High Rise Barrel Jeans',
            description: 'Sustainable and timeless piece from Reformation',
            price: '168.00',
            category: 'bottoms',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1322567BLU.jpg',
            stock: 19,
            sku: '1322567BLU',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Parker Pant',
            description: 'Sustainable and timeless piece from Reformation',
            price: '148.00',
            category: 'bottoms',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1322890TAN.jpg',
            stock: 33,
            sku: '1322890TAN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Devon Pant',
            description: 'Sustainable and timeless piece from Reformation',
            price: '148.00',
            category: 'bottoms',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1323123BLK.jpg',
            stock: 37,
            sku: '1323123BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Sets (4 products)
        {
            name: 'Ines Two Piece Set',
            description: 'Sustainable and timeless piece from Reformation',
            price: '298.00',
            category: 'sets',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1323456RED.jpg',
            stock: 21,
            sku: '1323456RED',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Jules Two Piece Set',
            description: 'Sustainable and timeless piece from Reformation',
            price: '268.00',
            category: 'sets',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1323789GRN.jpg',
            stock: 16,
            sku: '1323789GRN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Lara Knit Set',
            description: 'Sustainable and timeless piece from Reformation',
            price: '248.00',
            category: 'sets',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1324012CAM.jpg',
            stock: 13,
            sku: '1324012CAM',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Marina Set',
            description: 'Sustainable and timeless piece from Reformation',
            price: '228.00',
            category: 'sets',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1324345NAV.jpg',
            stock: 25,
            sku: '1324345NAV',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Outerwear (3 products)
        {
            name: 'Oversized Denim Jacket',
            description: 'Sustainable and timeless piece from Reformation',
            price: '248.00',
            category: 'outerwear',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1324678DEN.jpg',
            stock: 30,
            sku: '1324678DEN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Wool Blazer',
            description: 'Sustainable and timeless piece from Reformation',
            price: '368.00',
            category: 'outerwear',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1324901CHR.jpg',
            stock: 14,
            sku: '1324901CHR',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Puffer Coat',
            description: 'Sustainable and timeless piece from Reformation',
            price: '428.00',
            category: 'outerwear',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1325234BLK.jpg',
            stock: 11,
            sku: '1325234BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Shoes (3 products)
        {
            name: 'Loafer Mule',
            description: 'Sustainable and timeless piece from Reformation',
            price: '198.00',
            category: 'shoes',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1325567BRN.jpg',
            stock: 27,
            sku: '1325567BRN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Strappy Heel',
            description: 'Sustainable and timeless piece from Reformation',
            price: '228.00',
            category: 'shoes',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1325890SLV.jpg',
            stock: 20,
            sku: '1325890SLV',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Ballet Flat',
            description: 'Sustainable and timeless piece from Reformation',
            price: '178.00',
            category: 'shoes',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1326123BLK.jpg',
            stock: 43,
            sku: '1326123BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        
        // Accessories (4 products)
        {
            name: 'Crossbody Bag',
            description: 'Sustainable and timeless piece from Reformation',
            price: '198.00',
            category: 'accessories',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1326456TAN.jpg',
            stock: 36,
            sku: '1326456TAN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Tote Bag',
            description: 'Sustainable and timeless piece from Reformation',
            price: '148.00',
            category: 'accessories',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1326789BLK.jpg',
            stock: 42,
            sku: '1326789BLK',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Leather Belt',
            description: 'Sustainable and timeless piece from Reformation',
            price: '78.00',
            category: 'accessories',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1327012BRN.jpg',
            stock: 48,
            sku: '1327012BRN',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Silk Scarf',
            description: 'Sustainable and timeless piece from Reformation',
            price: '98.00',
            category: 'accessories',
            imageUrl: 'https://media.thereformation.com/image/upload/c_scale,w_1200/v1/prod/1327345FLR.jpg',
            stock: 34,
            sku: '1327345FLR',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});